### PR TITLE
update aria-checked messages

### PR DESCRIPTION
**Pull request by scottaohara**
add additional logic for checkbox and radio buttons with aria-checked.

@gezlemon please let me know if this updated logic will work correctly.

### CODE REVIEW

**Comment by gezlemon** [comment]
Hi @scottaohara, I haven't tested it, but it looks like it would work. I would move the return false statement to one statement at the end of the section for checkboxes, rather than having a separate statement for the if/else sections. All looks good with the radio part.

**Comment by scottaohara** [comment]
Thanks @gezlemon.  made that change re: return false.

**Comment by gezlemon** [comment]
Thanks, @scottaohara I've updated the bookmarklet.

**Comment by scottaohara** [comment]
heya @gezlemon.  just making sure the push was made so that the bookmarklet updates.  not noticing a difference when performing a test right now

**Comment by gezlemon** [comment]
Hi @scottaohara, sorry about that. I've just loaded it up again and tested it, and it's using the updated script now.

**Comment by scottaohara** [comment]
thank you gez.  looks good now!

**Pull request merged**
